### ISSUE TITLE
show-snps: command not found

### ISSUE THREAD

**Issue by liserjrqlxue** [PacificBiosciences/targeted-phasing-consensus#1]
I have installed SMRT Analysis v2.3.0.140936 and patched 2.3.0.140936.p4 as Running targeted-phasing-consensus.sh requires having SMRT Analysis 2.3.0 installed. But I got an error "targeted-phasing-consensus.sh: line 91: show-snps: command not found" and found that I didn't have program or script named show-snps in my SMRT Analysis which is suggested should there by targeted-phasing-consensus.sh script. How can I got a 'show-snps' to finished the last step of targeted-phasing-consensus?

Here are the last ten lines of log：
# process 49647 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /vol6/home/bgi_pacbio/.smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/mummer out.ntref 2.28
# reading input file "/vol6/home/bgi_pacbio/.smrtanalysis/userdata/jobs/016/016473/TPC/MHC/consensus1.fasta" of length 4963097
# matching query-file "/vol6/home/bgi_pacbio/.smrtanalysis/userdata/jobs/016/016473/TPC/MHC/consensus1.fasta"
# against subject-file "out.ntref"
# COMPLETETIME /vol6/home/bgi_pacbio/.smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/mummer out.ntref 8.10
# SPACE /vol6/home/bgi_pacbio/.smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/mummer out.ntref 9.63
4: FINISHING DATA
/vol6/home/bgi_pacbio/.smrtanalysis/current/analysis/bin/targeted-phasing-consensus.sh: line 91: show-snps: command not found

**Comment by lhon** [comment]
I thought show-snps was part of SMRT Analysis when testing, but apparently it isn't. So I've commented out the command. show-snps is part of the Mummer package, so you can install that to get the command.
