### ISSUE TITLE
Minimum coverage for the Samtools phasing.

### ISSUE THREAD

**Issue by WilsonCheng07** [PacificBiosciences/targeted-phasing-consensus#5]
Hi,
As I know from the pacbio webinar, in the process of the LAA, we need at least 200X coverage for an amplicon to generate the final consensus.  (cluster and phase).
So I'm wondering what is the **minimum coverage** for this script?

**Comment by rhallPB** [comment]
The LAA coverage relates to subreads, not CCS reads. For the script a minimum coverage is ~20x (10x per haplotype consensus). This is in line with the LAA recommendations given ~10 CCS passes, which would be the case for 2-3kb inserts.

**Comment by WilsonCheng07** [comment]
Thanks for the explanation, looks like we need a high accurate CCS to call the variants and phase the allele.

**Comment by WilsonCheng07** [comment]
Thanks for the explanation, looks like we need a high accurate CCS to call the variants and phase the allele.
